services:

  postgres:
    image: postgres:17
    container_name: ahe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ahe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ahe_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - myapp-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: unless-stopped
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --loose
      --skipApiVersionCheck
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - ./azurite-data:/data

volumes:
  postgres_data:

networks:
  myapp-network:
    driver: bridge